sources:
  - slug: icf-cdmx
    name: Iglesia Conquistando Fronteras
    preacher: ICF CDMX
    url: https://www.youtube.com/@ICFCDMX/videos
    enabled: true
  - slug: andres-spyker
    name: Andrés Spyker
    preacher: Andrés Spyker
    url: https://www.youtube.com/@Andr%C3%A9sSpyker/videos
    enabled: true
